version: '3.1'
services:
  mysql-db:
    image: mysql:latest
    environment:
      # MYSQL_USER: root # default
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampledb
    ports:
      - "3306:3306"
    volumes:
      - ./.tmp/data/mysql:/var/lib/mysql

  postgres-db:
    image: postgres:13
    environment:
      # POSTGRES_USER: postgres # default
      POSTGRES_PASSWORD: example
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"
    volumes:
      - ./.tmp/data/postgresql:/var/lib/postgresql/data

  mssql-db:
    platform: linux/arm64/v8
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: Y
      # SA_USER: sa # default
      SA_PASSWORD: "YourStrong(!Passw0rd)"
      # MSSQL_DATABASE: master # default, leave blank for sign in.
      MSSQL_PID: Developer # default
      # MSSQL_AGENT_ENABLED: true # default
      # MSSQL_COLLATION: SQL_Latin1_General_CP1_CI_AS # default
      # MSSQL_LCID: 1033 # default
      # MSSQL_MEMORY_LIMIT_MB: 2048 # default
      # MSSQL_TCP_PORT: 1433 # default
    ports:
      - "1433:1433"
    volumes:
      - ./.tmp/data/mssql:/var/opt/mssql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
