#
#  docker build -t alpine-sqlite -f Dockerfile.sqlite .
#
FROM alpine:latest
# Install SQLite
RUN apk update && apk upgrade
RUN apk add --no-cache sqlite
# Create a directory to store the database
WORKDIR /db

# Expose the port if needed
# EXPOSE 1433

# Command to run when the container starts
CMD ["sqlite3"]
