CREATE TABLE dbo.users (
  id INT IDENTITY(1, 1) PRIMARY KEY,
  username NVARCHAR(255) UNIQUE NOT NULL,
  password_hash NVARCHAR(255) NOT NULL,
  email NVARCHAR(255) UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);